import React, { useState } from 'react';
import {
  Scale,
  Plus,
  Search,
  CheckCircle2,
  AlertTriangle,
  FileSpreadsheet,
  Download,
  Calendar,
  Lock,
} from 'lucide-react';
import { JournalEntry, CompanyProfile } from '../types/accounting';

interface GeneralJournalViewProps {
  journalEntries: JournalEntry[];
  company: CompanyProfile;
  onOpenManualJournalModal: () => void;
}

export const GeneralJournalView: React.FC<GeneralJournalViewProps> = ({
  journalEntries,
  company,
  onOpenManualJournalModal,
}) => {
  const [searchTerm, setSearchTerm] = useState('');
  const currency = company.currencySymbol || '$';

  const filteredEntries = journalEntries.filter((entry) => {
    return (
      entry.memo.toLowerCase().includes(searchTerm.toLowerCase()) ||
      entry.entryNumber.toLowerCase().includes(searchTerm.toLowerCase()) ||
      entry.lines.some(
        (l) =>
          l.accountName.toLowerCase().includes(searchTerm.toLowerCase()) ||
          l.accountCode.includes(searchTerm)
      )
    );
  });

  return (
    <div className="space-y-6">
      {/* High Density Filter and Add Bar */}
      <div className="bg-white border border-slate-200 p-3.5 rounded-xl shadow-2xs flex flex-col sm:flex-row items-center justify-between gap-3">
        <div className="relative flex-1 w-full">
          <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            placeholder="Search journal entries by memo, entry number, or account name..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-9 pr-3 py-1.5 rounded-lg bg-slate-50 border border-slate-200 text-xs text-slate-900 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-600"
          />
        </div>

        <button
          onClick={onOpenManualJournalModal}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-indigo-600 hover:bg-indigo-700 text-white transition-colors cursor-pointer shadow-2xs whitespace-nowrap"
        >
          <Plus className="w-3.5 h-3.5" />
          <span>New Journal Entry</span>
        </button>
      </div>

      {/* Journal Entries Stream */}
      <div className="space-y-4">
        {filteredEntries.length === 0 ? (
          <div className="p-12 text-center bg-white border border-slate-200 rounded-xl text-slate-400 text-xs font-medium shadow-2xs">
            No journal entries match your search criteria.
          </div>
        ) : (
          filteredEntries.map((entry) => {
            const isBalanced = entry.isBalanced;

            return (
              <div
                key={entry.id}
                className="bg-white border border-slate-200 rounded-xl overflow-hidden shadow-2xs"
              >
                {/* Entry Header */}
                <div className="p-3.5 bg-slate-50 border-b border-slate-200 flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-xs">
                  <div className="flex items-center gap-3">
                    <span className="font-mono font-bold text-xs bg-indigo-50 text-indigo-700 px-2 py-0.5 rounded border border-indigo-200">
                      {entry.entryNumber}
                    </span>
                    <span className="font-bold text-slate-900">{entry.memo}</span>
                    {entry.isAutoGenerated && (
                      <span className="text-[10px] bg-slate-200 text-slate-700 font-semibold px-1.5 py-0.2 rounded">
                        Auto-Posted
                      </span>
                    )}
                  </div>

                  <div className="flex items-center gap-4">
                    <span className="text-slate-500 font-mono text-[11px]">{entry.date}</span>
                    <div className="flex items-center gap-1">
                      {isBalanced ? (
                        <span className="flex items-center gap-1 text-[10px] font-bold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-full border border-emerald-200">
                          <CheckCircle2 className="w-3 h-3 text-emerald-600" />
                          <span>Balanced</span>
                        </span>
                      ) : (
                        <span className="flex items-center gap-1 text-[10px] font-bold text-rose-700 bg-rose-50 px-2 py-0.5 rounded-full border border-rose-200">
                          <AlertTriangle className="w-3 h-3 text-rose-600" />
                          <span>Imbalance</span>
                        </span>
                      )}
                    </div>
                  </div>
                </div>

                {/* Double Entry Lines Table */}
                <div className="overflow-x-auto">
                  <table className="w-full text-left text-xs">
                    <thead className="bg-slate-50/50 text-slate-400 uppercase text-[10px] font-bold border-b border-slate-200">
                      <tr>
                        <th className="px-4 py-2">Account Code & Name</th>
                        <th className="px-4 py-2">Line Memo / Reference</th>
                        <th className="px-4 py-2 text-right">Debit (Dr)</th>
                        <th className="px-4 py-2 text-right">Credit (Cr)</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100 font-mono">
                      {entry.lines.map((line, idx) => {
                        const isCredit = line.credit > 0;
                        return (
                          <tr key={idx} className="hover:bg-slate-50/60 transition-colors">
                            <td className="px-4 py-2 font-sans">
                              <div className={`flex items-center ${isCredit ? 'pl-6 text-slate-600' : 'text-slate-900 font-medium'}`}>
                                <span className="font-mono text-slate-400 mr-2 text-[11px]">
                                  {line.accountCode}
                                </span>
                                <span>{line.accountName}</span>
                              </div>
                            </td>
                            <td className="px-4 py-2 text-slate-500 font-sans truncate max-w-xs">
                              {line.description || '-'}
                            </td>
                            <td className="px-4 py-2 text-right font-bold text-slate-800">
                              {line.debit > 0 ? `${currency}${line.debit.toLocaleString()}` : '-'}
                            </td>
                            <td className="px-4 py-2 text-right font-bold text-slate-800">
                              {line.credit > 0 ? `${currency}${line.credit.toLocaleString()}` : '-'}
                            </td>
                          </tr>
                        );
                      })}
                      {/* Entry Totals */}
                      <tr className="bg-slate-50 font-bold text-slate-900 text-xs border-t border-slate-200">
                        <td colSpan={2} className="px-4 py-2 font-sans text-right text-slate-500">
                          Total Entry Sum:
                        </td>
                        <td className="px-4 py-2 text-right font-mono text-indigo-700 font-bold">
                          {currency}{entry.totalDebit.toLocaleString()}
                        </td>
                        <td className="px-4 py-2 text-right font-mono text-indigo-700 font-bold">
                          {currency}{entry.totalCredit.toLocaleString()}
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
};
